# Generated by Django 5.0.3 on 2024-03-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_eats', '0002_remove_recipe_categories_recipe_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_pub',
            field=models.DateTimeField(null=True),
        ),
    ]
